---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Subnets:
    Type: String
    Default: subnet-0a6552f1afb6eb562
  KeyName:
    Type: String
    Default: MyWebServerDMZ
  InstanceSecurityGroup:
    Type: String
    Default: sg-0879fc0d794e7b3cf
  AMIId:
    Type: String
    Default: ami-04681a1dbd79675a5
  InstanceType:
    Type: String
    Default: t2.micro

Resources:
  WebServerGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        -
           Ref: Subnets
      LaunchConfigurationName:
        Ref: LaunchConfig
      MinSize: '1'
      MaxSize: '1'
      DesiredCapacity: '1'
      HealthCheckType: EC2
      HealthCheckGracePeriod: 600

  LaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      KeyName:
        Ref: KeyName
      ImageId:
        Ref: AMIId
      SecurityGroups:
      - Ref: InstanceSecurityGroup
      InstanceType:
        Ref: InstanceType