Resources:
  JKFirstRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 8
      DBInstanceIdentifier: pendyala-inst
      DBInstanceClass: db.t1.micro
      DBName: pendyaladb
      Engine: MySQL
      EngineVersion: 5.7
      MasterUsername: pendyalauser
      MasterUserPassword: pendyalauser1