Resources:
  JKFirstRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 8
      DBInstanceIdentifier: pendyala-inst
      DBInstanceClass: db.t2.small
      DBName: pendyaladb
      Engine: MySQL
      EngineVersion: 5.7
      MasterUsername: pendyalauser
      MasterUserPassword: pendyalauser1
      VPCSecurityGroups:
         - sg-0bc91df3dc4a6c8b9s