Resources:
  JKFirstRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 8
      DBInstanceIdentifier: pendyala-inst
      DBName: pendyaladb
      Engine: MySQL
      EngineVersion: 5.7
      MasterUsername: pendyalauser
      MasterPassword: pendyalauser1